#!/bin/sh 
set -e

source `dirname $0`/../configs.sh

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t libraoffice_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo ">>> Downloading libraoffice"

lb_local_path=$tempdir/LibreOffice_${LIRAOFFICE_VERSION}_Linux_x86-64_deb.tar.gz
lb_sources=$tempdir/LibreOffice_${LIRAOFFICE_VERSION}_Linux_x86-64_deb.tar.gz
curl http://ftp.nluug.nl/office/libreoffice/libreoffice/stable/${LIRAOFFICE_VERSION}/deb/x86_64/LibreOffice_${LIRAOFFICE_VERSION}_Linux_x86-64_deb.tar.gz

tar -C $tempdir -x -z -f $lb_sources

echo ">>> Building libraoffice"

vulcan build -v \
  -s $tempdir/Libraoffice-$LIRAOFFICE_VERSION \
  -n libraoffice\
  -o $lb_local_path

$basedir/aws/s3 put $S3_BUCKET $REMOTE_PATH $lb_local_path
